### ISSUE TITLE
[grails-aws-sdk-ses] Is it possible to send email to multiple recipients?

### ISSUE THREAD

**Issue by hamza3202** [agorapulse/grails-aws-sdk#55]
I cannot find support to send email to multiple recipients. Is it not possible?

**Comment by musketyr** [comment]
SES's `Destination` allows adding multiple emails:
http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/index.html?com/amazonaws/services/simpleemail/model/Destination.html

Where exactly you are missing the ability to add multiple recipients?

**Comment by musketyr** [comment]
@hamza3202 for the email DSL you can use `recipients(List<String> emails)` instead of `to(String email)`

**Comment by hamza3202** [comment]
Both the mail and send methods in AmazonSESService internally user AwsSesMailer's send method, which expects a single String as destination email. AmazonSESService's mail method does support the recipients parameter but when it calls the mailer.send method it only passes the first email from the list.

**Comment by musketyr** [comment]
I see, thanks for explanation. than it is definitely a bug

**Comment by romanye** [comment]
Looks like this is still a bug because I am getting this exception when using version 2.2.3 of the plugin:
_**Caused by: groovy.lang.MissingMethodException: No signature of method: com.agorapulse.awssdk.ses.AwsSesMailer.send() is applicable for argument types: (java.util.ArrayList, java.lang.String, java.lang.String, java.lang.String, java.lang.String)**_

**Comment by musketyr** [comment]
see the other issue, should be fixed in 2.2.4
